enabled: true
copyright: '<a href="http://blacktie.co/">Designed by blacktie.co</a> | Copyright 2015'
video_webm: 'http://alvarez.is/bt/appi.webm'
video_mp4: 'http://alvarez.is/bt/appi.mp4'
background_image: bg.jpg
